version: "3.9"

services:
  redis:
    image: redis:6.2-alpine
    networks:
      - app

  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app

  nginx_react:
    build:
      context: ./src
      target: prod-frontend
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
    networks:
      - app
      - proxy_fdlr_prod
    depends_on:
      - django

  django:
    build:
      context: ./src
      target: prod-backend
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_EXTERNAL_URL
      - VIRTUAL_HOST=${VIRTUAL_HOST_DJANGO}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST_DJANGO}
      - ALLOWED_HOSTS=${VIRTUAL_HOST},${VIRTUAL_HOST_DJANGO}
    networks:
      - app
      - proxy_fdlr_prod

  minio:
    image: bitnami/minio:2021.11.9
    entrypoint: []
    command: /bin/sh -c "mkdir -p /data/fdlr; exec /opt/bitnami/scripts/minio/entrypoint.sh /opt/bitnami/scripts/minio/run.sh"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_MINIO}
      - VIRTUAL_PORT=9000
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    volumes:
      - minio:/data
    networks:
      - app
      - proxy_fdlr_prod

networks:
  proxy_fdlr_prod:
    external: true
  app:

volumes:
  postgres:
  minio:
