version: "3.9"

services:
  redis:
    image: redis:6.2-alpine
    networks:
      - app

  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app

  nginx_react:
    build:
      context: ./src
      target: prod-frontend
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
    networks:
      - app
      - proxy_fdlr_prod
    depends_on:
      - django

  django:
    build:
      context: ./src
      target: prod-backend
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - VIRTUAL_HOST=${VIRTUAL_HOST_DJANGO}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST_DJANGO}
      - ALLOWED_HOSTS=${VIRTUAL_HOST},${VIRTUAL_HOST_DJANGO}
    networks:
      - app
      - proxy_fdlr_prod


networks:
  proxy_fdlr_prod:
    external: true
  app:

volumes:
  postgres:
  minio:
