# Generated by Django 3.2.9 on 2021-11-16 16:22

import common.models
import common.storages
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', common.models.BigCharField(max_length=1048576, verbose_name='name')),
                ('description', common.models.BigCharField(blank=True, max_length=1048576, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', common.models.BigCharField(max_length=1048576, verbose_name='name')),
                ('description', common.models.BigCharField(blank=True, max_length=1048576, verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
        migrations.CreateModel(
            name='Housemate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', common.models.BigCharField(max_length=1048576, verbose_name='name')),
                ('phone', common.models.BigCharField(blank=True, max_length=1048576, verbose_name='phone')),
                ('avatar', models.FileField(blank=True, storage=common.storages.MinioStorageInline, upload_to='', verbose_name='avatar')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housemates', to='households.household', verbose_name='household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='housemates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('description', common.models.BigCharField(blank=True, max_length=1048576, verbose_name='description')),
                ('transaction_type', common.models.BigCharField(choices=[('meal', 'Meal'), ('expense_group', 'Expense group'), ('other', 'Other'), ('initial', 'Initial')], max_length=1048576, verbose_name='transaction type')),
                ('amount', models.PositiveIntegerField(help_text='in cents', verbose_name='amount')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='households.housemate', verbose_name='creator')),
                ('expense_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='households.expensegroup', verbose_name='expense group')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='households.household', verbose_name='household')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='in cents', verbose_name='amount')),
                ('benefactor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='households.housemate')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='households.housemate')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='households.household', verbose_name='household')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='households.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateTimeField(blank=True, null=True, verbose_name='expiry')),
                ('token', common.models.BigCharField(max_length=1048576, verbose_name='token')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='households.household', verbose_name='household')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalExpenseGroupStake',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('stake', models.PositiveSmallIntegerField(verbose_name='stake')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('expense_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='households.expensegroup', verbose_name='expense group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('housemate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='households.housemate', verbose_name='housemate')),
            ],
            options={
                'verbose_name': 'historical expense group stake',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExpenseGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', common.models.BigCharField(max_length=1048576, verbose_name='name')),
                ('description', common.models.BigCharField(blank=True, max_length=1048576, verbose_name='description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='households.household', verbose_name='household')),
            ],
            options={
                'verbose_name': 'historical expense group',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ExpenseGroupStake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.PositiveSmallIntegerField(verbose_name='stake')),
                ('expense_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes', to='households.expensegroup', verbose_name='expense group')),
                ('housemate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stakes', to='households.housemate', verbose_name='housemate')),
            ],
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_groups', to='households.household', verbose_name='household'),
        ),
    ]
