version: "3.9"

services:
  redis:
    image: redis:6.2-alpine
    networks:
      - app

  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app

  nginx:
    build:
      context: ./src
      target: dev-proxy
    environment:
      - VIRTUAL_HOST
    networks:
      - app
      - proxy_fdlr_dev
    depends_on:
      - django
      - react

  django:
    build:
      context: ./src
      target: dev-backend
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_EXTERNAL_URL=http://${VIRTUAL_HOST_MINIO}
      - VIRTUAL_HOST=${VIRTUAL_HOST_DJANGO}
      - ALLOWED_HOSTS=${VIRTUAL_HOST},${VIRTUAL_HOST_DJANGO}
      - DEBUG=True
    volumes:
      - ./src/backend/:/app/
    networks:
      - app
      - proxy_fdlr_dev

  react:
    build:
      context: ./src
      target: dev-frontend
    networks:
      - app
    volumes:
      - ./src/frontend/public/:/app/public/
      - ./src/frontend/src/:/app/src/
      - ./src/frontend/craco.config.js:/app/craco.config.js
      - ./src/frontend/tailwind.config.js:/app/tailwind.config.js

  minio:
    image: bitnami/minio:2021.11.9
    entrypoint: []
    command: /bin/sh -c "mkdir -p /data/fdlr; exec /opt/bitnami/scripts/minio/entrypoint.sh /opt/bitnami/scripts/minio/run.sh"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_MINIO}
      - VIRTUAL_PORT=9000
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    volumes:
      - minio:/data
    networks:
      - app
      - proxy_fdlr_dev

  mailhog:
    image: mailhog/mailhog
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_MAILHOG}
      - VIRTUAL_PORT=8025
    expose:
      - 1025
      - 8025
    networks:
      - app
      - proxy_fdlr_dev

  adminer:
    image: adminer
    networks:
      - app
      - proxy_fdlr_dev
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - VIRTUAL_HOST=${VIRTUAL_HOST_ADMINER}
      - VIRTUAL_PORT=8080
    expose:
      - 8080

networks:
  proxy_fdlr_dev:
    external: true
  app:

volumes:
  postgres:
  minio:
